In [46]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [5]:
type(a)

numpy.ndarray

In [7]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [11]:
#creating 2d array 
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [12]:
#creating a 3d array 
a3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12,]],
                [[13,14,15],[16,17,18]]]) 
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [13]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [15]:
print(a2.ndim)
print(a3.ndim)

2
3


In [16]:
print(a2.dtype)

int64


In [17]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [26]:
np.random.randint(1,11, size=(4,2,3))

array([[[ 8,  7,  2],
        [ 9,  5,  5]],

       [[ 3,  3,  8],
        [ 7,  9,  5]],

       [[ 1, 10,  3],
        [ 3,  1,  1]],

       [[ 3,  1,  9],
        [ 6,  4,  6]]], dtype=int32)

In [27]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[15  7]
 [18 10]]
[[ 4  6]
 [10  2]]


In [28]:
print(x+y)
print(x-y)
print(x*y)

[[19 13]
 [28 12]]
[[11  1]
 [ 8  8]]
[[ 60  42]
 [180  20]]


In [29]:
#matrix multiplication 
#1st mathod
print(x @ y)

[[130 104]
 [172 128]]


In [30]:
#2nd method 
np.dot(x,y)

array([[130, 104],
       [172, 128]], dtype=int32)

In [31]:
x.prod()

np.int64(18900)

In [33]:
x.mean()
y.mean()

np.float64(5.5)

In [36]:
print(x)

[[15  7]
 [18 10]]


In [34]:
b = x.mean(axis=0)  #column wise
print(b)

[16.5  8.5]


In [35]:
c = x.mean(axis=1)   #row wise
print(c)

[11. 14.]


In [37]:
print(x.sum())
print(x.std())
print(x.var())


50
4.272001872658765
18.25


In [40]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.5
3.25
7.75


In [42]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[23 75 86 73]
 [47 38 12 61]
 [36 40 37 86]
 [28 39 37 63]]


In [44]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[23 75 86 73 47 38 12 61]
 [36 40 37 86 28 39 37 63]]
8x2
[[23 75]
 [86 73]
 [47 38]
 [12 61]
 [36 40]
 [37 86]
 [28 39]
 [37 63]]
