In [35]:
import numpy as np

In [36]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [37]:
type(a)

numpy.ndarray

In [38]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [39]:
#creating 2d array 
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [40]:
#creating a 3d array 
a3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12,]],
                [[13,14,15],[16,17,18]]]) 
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [41]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [42]:
print(a2.ndim)
print(a3.ndim)

2
3


In [43]:
print(a2.dtype)

int64


In [44]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [47]:
np.random.randint(1,11, size=(4,2,3))

array([[[ 1,  6,  5],
        [ 3,  2,  4]],

       [[10,  4,  6],
        [ 7, 10,  3]],

       [[ 2,  3,  8],
        [ 3,  2,  6]],

       [[ 4,  8,  9],
        [ 1,  6,  2]]], dtype=int32)

In [48]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[ 5 16]
 [11  2]]
[[ 3 11]
 [ 3  5]]


In [49]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 27]
 [14  7]]
[[ 2  5]
 [ 8 -3]]
[[ 15 176]
 [ 33  10]]


In [50]:
#matrix multiplication 
#1st mathod
print(x @ y)

[[ 63 135]
 [ 39 131]]


In [51]:
#2nd method 
np.dot(x,y)

array([[ 63, 135],
       [ 39, 131]], dtype=int32)

In [52]:
x.prod()

np.int64(1760)

In [53]:
x.mean()
y.mean()

np.float64(5.5)

In [54]:
print(x)

[[ 5 16]
 [11  2]]


In [55]:
b = x.mean(axis=0)  #column wise
print(b)

[8. 9.]


In [56]:
c = x.mean(axis=1)   #row wise
print(c)

[10.5  6.5]


In [57]:
print(x.sum())
print(x.std())
print(x.var())


34
5.408326913195984
29.25


In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.5
3.25
7.75


In [59]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[50 49 80 35]
 [11 66 74 46]
 [24 16 94 46]
 [49 75 78 55]]


In [60]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[50 49 80 35 11 66 74 46]
 [24 16 94 46 49 75 78 55]]
8x2
[[50 49]
 [80 35]
 [11 66]
 [74 46]
 [24 16]
 [94 46]
 [49 75]
 [78 55]]


In [61]:
print(arr2)

[[50 49 80 35]
 [11 66 74 46]
 [24 16 94 46]
 [49 75 78 55]]


In [62]:
print(arr2[0])     #0th row
print(arr2[0,1])   #0th row 1st column 
print(arr2[-1])    #last row 
print(arr2[:3])    #0th to 2nd row 
print(arr2[1:])    #1st to last row

[50 49 80 35]
49
[49 75 78 55]
[[50 49 80 35]
 [11 66 74 46]
 [24 16 94 46]]
[[11 66 74 46]
 [24 16 94 46]
 [49 75 78 55]]


In [83]:
arr2 > 60


array([[False, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [84]:
y = arr2[arr2>60]
z = y.reshape(1,4)
print(z)

ValueError: cannot reshape array of size 6 into shape (1,4)