In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [5]:
#creating 2d array 
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating a 3d array 
a3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12,]],
                [[13,14,15],[16,17,18]]]) 
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [7]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [8]:
print(a2.ndim)
print(a3.ndim)

2
3


In [9]:
print(a2.dtype)

int64


In [10]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.random.randint(1,11, size=(4,2,3))

array([[[ 8,  7,  2],
        [ 4,  6,  1]],

       [[10,  2,  6],
        [ 9,  8,  3]],

       [[ 3,  2, 10],
        [ 4,  7,  7]],

       [[ 6,  7,  3],
        [ 6,  5,  8]]], dtype=int32)

In [14]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[10  1]
 [15 16]]
[[ 6 10]
 [ 3  7]]


In [15]:
print(x+y)
print(x-y)
print(x*y)

[[16 11]
 [18 23]]
[[ 4 -9]
 [12  9]]
[[ 60  10]
 [ 45 112]]


In [16]:
#matrix multiplication 
#1st mathod
print(x @ y)

[[ 63 107]
 [138 262]]


In [17]:
#2nd method 
np.dot(x,y)

array([[ 63, 107],
       [138, 262]], dtype=int32)

In [18]:
x.prod()

np.int64(2400)

In [19]:
x.mean()
y.mean()

np.float64(6.5)

In [20]:
print(x)

[[10  1]
 [15 16]]


In [21]:
b = x.mean(axis=0)  #column wise
print(b)

[12.5  8.5]


In [22]:
c = x.mean(axis=1)   #row wise
print(c)

[ 5.5 15.5]


In [23]:
print(x.sum())
print(x.std())
print(x.var())


42
5.937171043518958
35.25


In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.5
3.25
7.75


In [25]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[54 65 95 19]
 [43 33 20 90]
 [73 88 70 87]
 [99 23 57 84]]


In [26]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[54 65 95 19 43 33 20 90]
 [73 88 70 87 99 23 57 84]]
8x2
[[54 65]
 [95 19]
 [43 33]
 [20 90]
 [73 88]
 [70 87]
 [99 23]
 [57 84]]


In [27]:
print(arr2)

[[54 65 95 19]
 [43 33 20 90]
 [73 88 70 87]
 [99 23 57 84]]


In [28]:
print(arr2[0])     #0th row
print(arr2[0,1])   #0th row 1st column 
print(arr2[-1])    #last row 
print(arr2[:3])    #0th to 2nd row 
print(arr2[1:])    #1st to last row

[54 65 95 19]
65
[99 23 57 84]
[[54 65 95 19]
 [43 33 20 90]
 [73 88 70 87]]
[[43 33 20 90]
 [73 88 70 87]
 [99 23 57 84]]


In [29]:
arr2 > 60


array([[False,  True,  True, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [30]:
y = arr2[arr2>60]
z = y.reshape(1,4)
print(z)

ValueError: cannot reshape array of size 9 into shape (1,4)